### ISSUE TITLE
[1.16.1] Item duping

### ISSUE THREAD

**Issue by djwild** [refinedmods/refinedstorage#2656]
#### Issue description:
Placing items down with a constructor doesnt actually use items in the disks ending in duplicating every item placing down.

- Minecraft: 1.16.1
- Forge: 32.0.108
- Refined Storage: 1.9.2
(tested with only RS, no other mods)

Does this issue occur on a server? SP and Server

**Comment by chastain1337** [comment]
I am also experiencing this using 1.9.2, Minecraft 1.16.1 but forge 32.0.106.

**Comment by lordnunu111** [comment]
Also experiencing this. Really disappointing actually

**Comment by tth05** [comment]
fixed in #2633

**Comment by djwild** [comment]
> 
> 
> fixed in #2633

Definitely isnt fixed, since people are still experiencing that.

**Comment by Darkere** [comment]
It was fixed. The fix not been released yet.

**Comment by djwild** [comment]
Oh ok sorry then still need to get used to the github thing :)
