### ISSUE TITLE
Issue with autocrafting fluids

### ISSUE THREAD

**Issue by levonalexanian** [refinedmods/refinedstorage#3298]
### Describe the bug

I was playing the mod pack Cave Factory, and was automating fluid crafting using refined storage. I couldn't get it to work with my set up so I saved the game and closed Minecraft without canceling a autocraft request and now whenever I open the world it crashes. If its relevant I was mixing Refined Storage with Tinkers Construct. 

The following is the start of the crash report:
Description: Exception in server tick loop

java.lang.IllegalStateException: Bad!
	at com.refinedmods.refinedstorage.apiimpl.autocrafting.task.v6.node.NodeRequirements.getSingleFluidRequirementSet(NodeRequirements.java:140) ~[?:1.9.16] {re:classloading}
	at com.refinedmods.refinedstorage.apiimpl.autocrafting.task.v6.node.ProcessingNode.update(ProcessingNode.java:123) ~[?:1.9.16] {re:classloading}
	at com.refinedmods.refinedstorage.apiimpl.autocrafting.task.v6.CraftingTask.update(CraftingTask.java:191) ~[?:1.9.16] {re:classloading}
	at com.refinedmods.refinedstorage.apiimpl.autocrafting.CraftingManager.updateTasks(CraftingManager.java:170) ~[?:1.9.16] {re:classloading}
	at com.refinedmods.refinedstorage.apiimpl.autocrafting.CraftingManager.update(CraftingManager.java:134) ~[?:1.9.16] {re:classloading}
	at com.refinedmods.refinedstorage.apiimpl.network.Network.update(Network.java:165) ~[?:1.9.16] {re:classloading}
	at com.refinedmods.refinedstorage.apiimpl.network.NetworkListener.onWorldTick(NetworkListener.java:17) ~[?:1.9.16] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_1736_NetworkListener_onWorldTick_WorldTickEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$3540/1025846869.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.fml.hooks.BasicEventHooks.onPostWorldTick(BasicEventHooks.java:100) ~[?:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:857) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterendforge.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterendforge.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:78) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterendforge.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterendforge.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer$$Lambda$27371/1042002421.run(Unknown Source) [?:?] {}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}

A detailed walkthrough of the error, its code path and all known details is as follows:

### How can we reproduce this bug or crash?

1. Set up autocrafting with fluids
2. Make a impossible request (like pump out 30 buckets of water when you only have 5 buckets)
3. Close the game.
4. Open the game
5. Open the world

### What Minecraft version is this happening on?

Minecraft 1.16.5

### What Forge version is this happening on?

Forge 36.2.23

### What Refined Storage version is this happening on?

The jar file is called "refinedstorage-1.9.16.jar" there is also "refinedstorageaddons-0.7.4.jar"

**Comment by Darkere** [comment]
A bug that caused this was fixed in 1.9.17.....

**Comment by levonalexanian** [comment]
Updated the file to 1.9.17, opened the world and it still crashed.  Is the world screwed or is there something I can do?

Here's the crash log:
[crash-2022-05-07_21.57.27-server.txt](https://github.com/refinedmods/refinedstorage/files/8646213/crash-2022-05-07_21.57.27-server.txt)

**Comment by Darkere** [comment]
Go to world/data/refinedstorage_networks.dat and open it with nbt explorer. You should be able to find your crafting task and delete it.
