### ISSUE TITLE
Items Missing - Crafting Grid

### ISSUE THREAD

**Issue by FrenchBullPuss** [refinedmods/refinedstorage#3693]
### Describe the bug

I am not sure if this has already been submitted:
Playing ATM9 and quite frequently the crafting grid ( including portable ) will show no items in the grid.
Grid shows power and breaking network controller and re placing does not fix.

This happens infrequently and up to a few times a session. The only way to resolve the issue is restarting PC ( not even client )
Latest version of Refined Storage.

At random times, re spamming items into the refined storage system brings back the grid items.
System still accepts items, importers and exporters also still function regardless of the grid items not showing.
The disk drive shows items adding to disks.

![image](https://github.com/refinedmods/refinedstorage/assets/171297338/4636a9f1-61f8-4b62-9c18-1093e342d79e)

### How can we reproduce this bug or crash?

I am able to force replicate the issue by using an auto clicker to auto craft using a Master Crystal and Inferium from Mystical Agriculture.

### What Minecraft version is this happening on?

Minecraft 1.20.1

### What Forge version is this happening on?

Version: 47.2.20

### What Refined Storage version is this happening on?

1.12.4

**Comment by FrenchBullPuss** [comment]
I will also note, it doesn't matter which disks i use or size. Still happens regardless of disk size.
Current configuration: x3 1024k ( extra disks mod ) | x1 16384k ( extra disks mod )
Version of Extra Disks: 3.0.2

**Comment by Nodrance** [comment]
> The only way to resolve the issue is restarting PC ( not even client )   

This is a graphics issue. There's no other way that restarting the game wouldn't fix it but pc would.

**Comment by EthanSn** [comment]
Had this happen to me restarted the modpack (ATM9) completely and all of my drives are gone.

**Comment by FrenchBullPuss** [comment]
> ###
> **[Nodrance](/Nodrance) ** commented [Jun 1, 2024](#issuecomment-2143334567) •

Yeah restarting PC fixes it temporarily until it occurs at random again.

**Comment by Penguinzfound** [comment]
I fixed it via reloading the textures (F3+T)

**Comment by xiHamad** [comment]
Still having the issue, I tried every solution above and nothing worked for me ^^
so is there any thing that can help?

**Comment by justinmulvin** [comment]
![Screenshot 2024-06-22 130645](https://github.com/refinedmods/refinedstorage/assets/173564719/ad78cf02-7c01-4c81-8433-659d280718e1)
![Screenshot 2024-06-22 130743](https://github.com/refinedmods/refinedstorage/assets/173564719/715d68db-66a6-426b-b6e3-86a35663faf9)
![Screenshot 2024-06-22 130700](https://github.com/refinedmods/refinedstorage/assets/173564719/3e62c081-cfc4-4f08-a031-b1f3e86344f1)
![Screenshot 2024-06-22 130729](https://github.com/refinedmods/refinedstorage/assets/173564719/e6d2730d-a3ba-4f73-9821-f614ecab200e)
I dont know if these help solve the issue but i learned that the any items that can be interacted with do not change position when you adjust the size of the display as you can see they are floating where they started instead of adjusting to the new size orientation when this issue is occuring. im not smart when it comes to coding or anything but it may have some impact on whats causing this issue to occur.

**Comment by Nodrance** [comment]
this might not help anything but do you know what kind of cpu and gpu you have? And do you ever update your graphics drivers?

**Comment by justinmulvin** [comment]
I personally have a gigabyte gaming rtx 3070ti and core i7 12700k graphics drivers are up to date. Also want to say that restarting pc doesn't help me and I had this same issue back in all the mods 8 as well and it was on my laptop also which is a hp omen older with a core i5 10500h and gtx 1650 gpu

**Comment by justinmulvin** [comment]
![Screenshot 2024-06-23 081549](https://github.com/refinedmods/refinedstorage/assets/173564719/fc6c973e-3145-41fe-8d9e-55af4baf4763)
![Screenshot 2024-06-23 081622](https://github.com/refinedmods/refinedstorage/assets/173564719/d85bdf21-4520-4d61-a472-d6890395d811)
![Screenshot 2024-06-23 081638](https://github.com/refinedmods/refinedstorage/assets/173564719/a2558f49-24c3-4535-b692-a3354e18e3ea)
![Screenshot 2024-06-23 081648](https://github.com/refinedmods/refinedstorage/assets/173564719/3522df07-3e42-4a1b-860f-0d87254f974d)
okay so i was playing this morning and attempting to find a work around and sent all the items to external storage and used the storage scanner from rftools as the work around and i noticed something that may show that this issue is actually somwhere else it just affects refined storage the most, or i could be having two seperate bugs at the same time.
